name: ant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy=1.9.3
  - mne=1.10.1
  - mne-connectivity=0.7.0
  - mne-features=0.3
  - matplotlib
  - scikit-learn
  - fooof
  - pyunlocbox=0.5.2
  - pip:
      - mne-lsl